"""
data/prepare_maze.py — generate the maze-navigation corpus.

Per the locked predictions file `predictions/predictions_maze_navigation.md`:
- 8×8 grid mazes generated by recursive backtracking (perfect mazes;
  exactly one path between any two cells).
- Each training sequence is `[BOS, start_cell, step_1, ..., goal_cell, EOS]`
  where each step token encodes the next cell visited on the BFS-optimal
  shortest path from start to goal.
- Maze-level split: train / val / gen mazes are disjoint — the model
  never sees a test maze's walls during training.

Outputs (under --out_dir):
    train.bin   uint16 token stream
    val.bin     uint16 token stream
    gen.bin     uint16 token stream
    meta.pkl    {vocab_size, stoi, itos, dtype, n_grid, ...}
    mazes.csv   per-position side table for the probe:
                split, maze_idx, token_pos, current_cell,
                start_cell, goal_cell, distance_to_goal,
                row, col

The probe-target columns (start_cell, goal_cell, distance_to_goal,
row, col) NEVER enter the model — they are read only by eval/probe_*
code from this CSV.

Destroyed-structure controls (mutually exclusive flags):
    --shuffle_within       shuffle token order within each path,
                           preserving BOS/EOS boundaries and the
                           per-maze cell-identity set. Tests whether
                           path order is required for encoding.
    --shuffle_globally     globally permute real cell tokens across
                           the corpus. Breaks cell identity too.

Usage:
    # Real corpus:
    python data/prepare_maze.py --n_mazes 100000 --out_dir data/maze_8x8

    # Within-shuffled control:
    python data/prepare_maze.py --n_mazes 100000 --shuffle_within \\
        --out_dir data/maze_8x8_within_shuffled

    # Global-shuffled control:
    python data/prepare_maze.py --n_mazes 100000 --shuffle_globally \\
        --out_dir data/maze_8x8_global_shuffled
"""
import argparse
import csv
import pickle
import random
import sys
from collections import deque
from pathlib import Path

import numpy as np

# ── Token reserved indices (must mirror the rest of the project) ──
PAD, BOS, EOS = 0, 1, 2
N_RESERVED = 3


# ──────────────────────────────────────────────────────────────────────
# Maze generation (recursive backtracking)
# ──────────────────────────────────────────────────────────────────────

def generate_maze(size: int, rng: random.Random) -> set:
    """Generate a perfect maze on a size×size grid via recursive
    backtracking. Returns the set of *open passages* — frozenset
    pairs `((r1, c1), (r2, c2))` representing cells that ARE
    connected (no wall between them).

    A perfect maze has exactly one simple path between any two cells.
    """
    visited = set()
    passages = set()
    stack = [(rng.randrange(size), rng.randrange(size))]
    visited.add(stack[0])

    while stack:
        r, c = stack[-1]
        # Find unvisited neighbors
        neighbors = []
        for dr, dc in ((-1, 0), (1, 0), (0, -1), (0, 1)):
            nr, nc = r + dr, c + dc
            if 0 <= nr < size and 0 <= nc < size and (nr, nc) not in visited:
                neighbors.append((nr, nc))
        if not neighbors:
            stack.pop()
            continue
        nxt = rng.choice(neighbors)
        # Open passage between current and nxt
        passages.add(frozenset(((r, c), nxt)))
        visited.add(nxt)
        stack.append(nxt)

    return passages


def cell_neighbors(cell, passages, size):
    """Return cells reachable from `cell` (i.e., no wall between them)."""
    r, c = cell
    out = []
    for dr, dc in ((-1, 0), (1, 0), (0, -1), (0, 1)):
        nr, nc = r + dr, c + dc
        if 0 <= nr < size and 0 <= nc < size:
            if frozenset(((r, c), (nr, nc))) in passages:
                out.append((nr, nc))
    return out


def bfs_shortest_path(passages, start, goal, size):
    """Return the shortest path from start to goal as a list of cells
    (inclusive of both endpoints). Returns None if unreachable
    (shouldn't happen in a perfect maze)."""
    if start == goal:
        return [start]
    visited = {start: None}
    q = deque([start])
    while q:
        cur = q.popleft()
        for nb in cell_neighbors(cur, passages, size):
            if nb not in visited:
                visited[nb] = cur
                if nb == goal:
                    # reconstruct
                    path = [goal]
                    while path[-1] != start:
                        path.append(visited[path[-1]])
                    path.reverse()
                    return path
                q.append(nb)
    return None  # unreachable (shouldn't happen)


# ──────────────────────────────────────────────────────────────────────
# Tokenization
# ──────────────────────────────────────────────────────────────────────

def cell_to_token(cell, size):
    r, c = cell
    return N_RESERVED + r * size + c


def token_to_cell(tok, size):
    idx = tok - N_RESERVED
    return (idx // size, idx % size)


def manhattan_distance(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])


def encode_path(path, size):
    """Returns list of ints: [BOS, t1, t2, ..., tn, EOS]."""
    return [BOS] + [cell_to_token(c, size) for c in path] + [EOS]


# ──────────────────────────────────────────────────────────────────────
# Destroyed-structure controls
# ──────────────────────────────────────────────────────────────────────

def shuffle_within(seq, rng):
    """Shuffle the interior of a single sequence, preserving BOS/EOS
    framing. The cell-identity set is preserved; the path order is
    destroyed."""
    assert seq[0] == BOS and seq[-1] == EOS
    interior = seq[1:-1]
    rng.shuffle(interior)
    return [BOS] + interior + [EOS]


def shuffle_globally(token_stream, vocab_size, rng):
    """Apply a random permutation to all real cell tokens (>= N_RESERVED).
    BOS/EOS/PAD are preserved in place. The vocabulary set is preserved
    but cell identities are scrambled."""
    real_ids = list(range(N_RESERVED, vocab_size))
    shuffled = list(real_ids)
    rng.shuffle(shuffled)
    remap = dict(zip(real_ids, shuffled))
    return [remap.get(t, t) for t in token_stream]


# ──────────────────────────────────────────────────────────────────────
# Corpus generation
# ──────────────────────────────────────────────────────────────────────

def generate_maze_records(n_mazes, size, min_path_len, max_path_len, rng):
    """Yield (passages, start, goal, path) tuples for n_mazes mazes."""
    py_rng = random.Random(rng.integers(0, 2**31).item())
    accepted = 0
    attempts = 0
    while accepted < n_mazes:
        attempts += 1
        passages = generate_maze(size, py_rng)
        # pick random start + goal
        start = (py_rng.randrange(size), py_rng.randrange(size))
        goal = (py_rng.randrange(size), py_rng.randrange(size))
        while goal == start:
            goal = (py_rng.randrange(size), py_rng.randrange(size))
        path = bfs_shortest_path(passages, start, goal, size)
        if path is None:
            continue
        if not (min_path_len <= len(path) <= max_path_len):
            continue
        accepted += 1
        yield passages, start, goal, path


def split_indices(n, val_frac, gen_frac, rng):
    perm = rng.permutation(n)
    n_val = int(n * val_frac)
    n_gen = int(n * gen_frac)
    val = set(perm[:n_val].tolist())
    gen = set(perm[n_val:n_val + n_gen].tolist())
    train = set(perm[n_val + n_gen:].tolist())
    return train, val, gen


# ──────────────────────────────────────────────────────────────────────
# Output (mirrors data/prepare_city.py and data/prepare_adsb.py)
# ──────────────────────────────────────────────────────────────────────

def pick_dtype(vocab_size):
    return np.uint16 if vocab_size < 65535 else np.uint32


def dump(out_dir, splits, side_rows, vocab_size, size, args):
    """Write train.bin / val.bin / gen.bin / meta.pkl / mazes.csv."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    dtype = pick_dtype(vocab_size)

    for split_name in ("train", "val", "gen"):
        arr = np.array(splits[split_name], dtype=dtype)
        arr.tofile(out / f"{split_name}.bin")

    stoi = {f"cell_{r}_{c}": cell_to_token((r, c), size)
            for r in range(size) for c in range(size)}
    stoi["<PAD>"] = PAD
    stoi["<BOS>"] = BOS
    stoi["<EOS>"] = EOS
    itos = {v: k for k, v in stoi.items()}

    meta = {
        "vocab_size": vocab_size,
        "stoi": stoi,
        "itos": itos,
        "dtype": np.dtype(dtype).name,
        "dtype_str": "uint16" if dtype == np.uint16 else "uint32",
        "n_grid": size,
        "domain": "maze_navigation",
        "shuffle_within": args.shuffle_within,
        "shuffle_globally": args.shuffle_globally,
        "n_mazes": args.n_mazes,
        "min_path_len": args.min_path_len,
        "max_path_len": args.max_path_len,
        "seed": args.seed,
    }
    with open(out / "meta.pkl", "wb") as f:
        pickle.dump(meta, f)

    with open(out / "mazes.csv", "w", newline="") as fcsv:
        writer = csv.DictWriter(
            fcsv,
            fieldnames=[
                "split", "maze_idx", "token_pos", "current_cell",
                "start_cell", "goal_cell", "distance_to_goal",
                "row", "col",
            ],
        )
        writer.writeheader()
        writer.writerows(side_rows)

    sizes = {k: len(splits[k]) for k in splits}
    n_unique_real_tokens = vocab_size - N_RESERVED
    print(f"wrote {out}")
    print(f"  train tokens: {sizes['train']:,}")
    print(f"  val tokens:   {sizes['val']:,}")
    print(f"  gen tokens:   {sizes['gen']:,}")
    print(f"  vocab size:   {vocab_size}  (real cells: {n_unique_real_tokens})")
    print(f"  side-table rows: {len(side_rows):,}")


# ──────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--out_dir", required=True)
    p.add_argument("--n_mazes", type=int, default=100_000)
    p.add_argument("--grid_size", type=int, default=8,
                   help="Maze is grid_size × grid_size. Default 8 matches predictions.")
    p.add_argument("--min_path_len", type=int, default=4,
                   help="Reject mazes whose start→goal BFS path is shorter than this.")
    p.add_argument("--max_path_len", type=int, default=30)
    p.add_argument("--val_frac", type=float, default=0.10)
    p.add_argument("--gen_frac", type=float, default=0.10)
    p.add_argument("--seed", type=int, default=0)
    g = p.add_mutually_exclusive_group()
    g.add_argument("--shuffle_within", action="store_true",
                   help="Shuffle token order within each path. Destroys path order, preserves cell identity.")
    g.add_argument("--shuffle_globally", action="store_true",
                   help="Globally permute real cell tokens across the corpus.")
    args = p.parse_args()

    size = args.grid_size
    vocab_size = N_RESERVED + size * size
    rng = np.random.default_rng(args.seed)

    print(f"Generating {args.n_mazes:,} mazes of size {size}×{size} ...")
    py_rng = random.Random(rng.integers(0, 2**31).item())
    records = []
    accepted = 0
    while accepted < args.n_mazes:
        passages = generate_maze(size, py_rng)
        start = (py_rng.randrange(size), py_rng.randrange(size))
        goal = (py_rng.randrange(size), py_rng.randrange(size))
        while goal == start:
            goal = (py_rng.randrange(size), py_rng.randrange(size))
        path = bfs_shortest_path(passages, start, goal, size)
        if path is None or not (args.min_path_len <= len(path) <= args.max_path_len):
            continue
        records.append((start, goal, path))
        accepted += 1
        if accepted % 10000 == 0:
            print(f"  {accepted:,} / {args.n_mazes:,}")

    print("Splitting mazes ...")
    train_set, val_set, gen_set = split_indices(
        args.n_mazes, args.val_frac, args.gen_frac, rng,
    )

    print("Encoding paths + building side table ...")
    splits = {"train": [], "val": [], "gen": []}
    side_rows = []
    side_rng = random.Random(args.seed)

    for maze_idx, (start, goal, path) in enumerate(records):
        if maze_idx in val_set:
            split_name = "val"
        elif maze_idx in gen_set:
            split_name = "gen"
        else:
            split_name = "train"

        # Encode
        tokens = encode_path(path, size)

        # Apply within-shuffle if requested
        if args.shuffle_within:
            tokens = shuffle_within(tokens, side_rng)

        # Per-position side-table rows (ALWAYS reference the REAL path,
        # so probes can read true labels even on shuffled corpora —
        # the probe target is the model's residual at THIS position;
        # the label is what cell IS at this position in the shuffled
        # sequence)
        offset_in_stream = len(splits[split_name])
        for pos_in_seq, tok in enumerate(tokens):
            if tok in (PAD, BOS, EOS):
                continue
            cell = token_to_cell(tok, size)
            row, col = cell
            side_rows.append({
                "split": split_name,
                "maze_idx": maze_idx,
                "token_pos": offset_in_stream + pos_in_seq,
                "current_cell": tok,
                "start_cell": cell_to_token(start, size),
                "goal_cell": cell_to_token(goal, size),
                "distance_to_goal": manhattan_distance(cell, goal),
                "row": row,
                "col": col,
            })

        splits[split_name].extend(tokens)

    # Optionally apply global shuffle (after side table is built — the
    # side table's `current_cell` field needs to be remapped too).
    if args.shuffle_globally:
        print("Applying global cell-token shuffle ...")
        real_ids = list(range(N_RESERVED, vocab_size))
        shuffled = list(real_ids)
        side_rng.shuffle(shuffled)
        remap = dict(zip(real_ids, shuffled))
        for split_name in splits:
            splits[split_name] = [remap.get(t, t) for t in splits[split_name]]
        # Remap side table too
        for row in side_rows:
            row["current_cell"] = remap.get(row["current_cell"], row["current_cell"])
            row["start_cell"] = remap.get(row["start_cell"], row["start_cell"])
            row["goal_cell"] = remap.get(row["goal_cell"], row["goal_cell"])

    dump(args.out_dir, splits, side_rows, vocab_size, size, args)


if __name__ == "__main__":
    main()
